kind: Service
apiVersion: v1
metadata:
  name: geo-cache-service
spec:
  type: NodePort
  selector:
    app: ThatTeam_GeoCache
  ports:
    - port: 3050 # used by other pods
      protocol: TCP
      targetPort: 8080 # port exposed on the container
      nodePort: 31515 # used to access from the outside

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: geocache-deployment
  labels:
    app: geo-cache-dep

spec:
  replicas: 1
  selector:
    matchLabels:
      app: ThatTeam_GeoCache
  template:
    metadata:
      labels:
        app: ThatTeam_GeoCache
    spec:
      containers:
        - name: geocache
          image: walldiv/project2_geocache
          ports:
            - containerPort: 8080 #due to containers being isolated - all these can be 8080 and not error out.
